spring.application.name=YoloBolo-Zeepkist-Appserver
spring.mongodb.uri=${MONGODB_URI:mongodb://localhost:27017/zeepkist}
steam.api.key=${STEAM_API_KEY:dummy}
zeepkist.app.id=1440670
server.port=${PORT:5000}
spring.mongodb.drop-on-startup=false